# Copyright(C) 2023  Sutou Kouhei <kou@clear-code.com>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License version 2.1 as published by the Free Software Foundation.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: "v15.0.7"
    hooks:
      - id: clang-format
        files: >-
          (
          ?include/groonga/command_arguments\.hpp|
          ?include/groonga/groonga\.h|
          ?include/groonga/highlighter\.h|
          ?include/groonga/obj\.h|
          ?include/groonga/proc\.h|
          ?include/groonga/table\.h|
          ?include/groonga/util\.h|
          ?lib/aggregators\.c|
          ?lib/alloc\.c|
          ?lib/arrow\.cpp|
          ?lib/cast\.cpp|
          ?lib/command_arguments\.cpp|
          ?lib/ctx\.c|
          ?lib/ctx_impl_mrb\.c|
          ?lib/db\.c|
          ?lib/error\.c|
          ?lib/expr\.c|
          ?lib/grn_ctx_impl\.h|
          ?lib/grn_error\.h|
          ?lib/grn_ii\.h|
          ?lib/grn_io\.h|
          ?lib/grn_load\.h|
          ?lib/grn_proc\.h|
          ?lib/grn_str\.h|
          ?lib/grn_table_selector\.h|
          ?lib/highlighter\.c|
          ?lib/ii\.c|
          ?lib/load\.c|
          ?lib/normalizer\.c|
          ?lib/mrb/mrb_ctx\.c|
          ?lib/mrb/mrb_error\.c|
          ?lib/obj\.c|
          ?lib/pat\.c|
          ?lib/proc/proc_column\.c|
          ?lib/proc/proc_highlight\.c|
          ?lib/proc/proc_object_inspect\.c|
          ?lib/proc/proc_select\.cpp|
          ?lib/proc\.c|
          ?lib/store\.c|
          ?lib/str\.c|
          ?lib/table_selector\.c|
          ?lib/tokenizer\.c|
          ?lib/util\.c|
          ?src/groonga\.c|
          )
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier
        files: >-
          (
          ?CMakePresets\.json|
          )

exclude: "^vendor/.*"
