name: macOS
on:
  push:
    branches:
      - master
      - 'maintenance/**'
    tags:
      - '*'
  pull_request:
concurrency:
  group: ${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  autotools:
    name: Autotools
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install packages
        run: |
          rm -f /usr/local/bin/2to3* || :
          rm -f /usr/local/bin/idle3* || :
          rm -f /usr/local/bin/pydoc3* || :
          rm -f /usr/local/bin/python3* || :
          rm -f /usr/local/bin/python3-config* || :
          brew update || :
          brew bundle
      - name: Generate configure
        run: |
          ./autogen.sh
      - name: Configure
        run: |
          mkdir -p ../groonga.build
          cd ../groonga.build
          ../groonga/configure \
            --enable-debug \
            --enable-mruby \
            --prefix=/tmp/local \
            --with-ruby \
            PKG_CONFIG_PATH=$(brew --prefix openssl)/lib/pkgconfig
      - name: Build
        run: |
          make -C ../groonga.build -j$(/usr/sbin/sysctl -n hw.ncpu)
      - name: Install test dependencies
        run: |
          MAKEFLAGS=-j$(nproc) gem install \
            groonga-client \
            json \
            pkg-config \
            red-arrow
      - name: Set environment variables
        run: |
          echo "COLUMNS=79" >> ${GITHUB_ENV}
      - name: "Test: stdio"
        run: |
          cd ../groonga.build
          BUILD_DIR=$PWD/test/command \
            bash -x ../groonga/test/command/run-test.sh \
              --n-retries=3 \
              --read-timeout=30 \
              --reporter=mark
      - name: Install
        run: |
          make -C ../groonga.build install
