name: "Windows MinGW"
on:
  - push
  - pull_request
jobs:
  build:
    name: Build
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            autoconf
            automake-wrapper
            git
            make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-libtool
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-python3-pip
            mingw-w64-x86_64-ruby
            mingw-w64-x86_64-xxhash
            mingw-w64-x86_64-zlib
      - name: Install Sphinx
        shell: msys2 {0}
        run: |
          pip3 install -U Sphinx
      - name: Generate configure
        shell: msys2 {0}
        run: |
          bash autogen.sh
      - name: Configure for archive
        shell: msys2 {0}
        run: |
          ./configure \
            --enable-document \
            --enable-mruby \
            --with-ruby \
            --without-zlib
      - name: Show config.log
        shell: msys2 {0}
        if: always()
        run: |
          cat config.log
      - name: Build archive
        shell: msys2 {0}
        run: |
          make dist
      - name: Configure
        shell: msys2 {0}
        run: |
          mkdir ../groonga.build
          cd ../groonba.build
          ../groonga/configure \
            --disable-groonga-httpd \
            --enable-mruby \
            --enable-shared-onigmo \
            --with-ruby
      - name: Show config.log
        shell: msys2 {0}
        if: always()
        run: |
          cat ../groonba.build/config.log
      - name: Build
        shell: msys2 {0}
        run: |
          cd ../groonba.build
          make -j${NUMBER_OF_PROCESSORS}
      - name: Install
        shell: msys2 {0}
        run: |
          cd ../groonba.build
          make install
